title: Project
sections:
  content:
    display: Content
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: slug
        field:
          type: slug
          localizable: true
          instructions_position: above
          listable: hidden
          visibility: visible
          always_save: false
          from: title
          generate: true
          validate:
            - required
            - 'unique_entry_value:{collection},{id},{site}'
      -
        handle: content_text
        field:
          collapse: false
          always_show_set_button: false
          previews: true
          smart_typography: false
          buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - image
            - table
          save_html: false
          inline: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          enable_input_rules: true
          enable_paste_rules: true
          antlers: false
          remove_empty_nodes: false
          display: Text
          type: bard
          icon: bard
          listable: hidden
          instructions_position: above
          visibility: visible
  media:
    display: Media
    fields:
      -
        handle: content_media
        field:
          collapse: false
          always_show_set_button: false
          previews: true
          smart_typography: false
          sets:
            image:
              display: Image
              fields:
                -
                  handle: image
                  field:
                    mode: list
                    container: assets
                    restrict: false
                    allow_uploads: true
                    show_filename: true
                    max_files: 1
                    display: Image
                    type: assets
                    icon: assets
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                -
                  import: columns
                -
                  import: maximum_width
                -
                  handle: caption
                  field:
                    antlers: false
                    display: Caption
                    type: textarea
                    icon: textarea
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                -
                  handle: link
                  field:
                    display: Link
                    type: link
                    icon: link
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    width: 50
                    container: assets
                -
                  handle: target
                  field:
                    options:
                      _self: 'Same window'
                      _blank: 'New window'
                    multiple: false
                    clearable: false
                    searchable: true
                    taggable: false
                    push_tags: false
                    cast_booleans: false
                    default: _self
                    display: Target
                    type: select
                    icon: select
                    width: 50
                    listable: hidden
                    instructions_position: above
                    visibility: visible
            video:
              display: Video
              fields:
                -
                  import: video
                -
                  import: columns
                -
                  handle: caption
                  field:
                    antlers: false
                    display: Caption
                    type: textarea
                    icon: textarea
                    listable: hidden
                    instructions_position: above
                    visibility: visible
          save_html: false
          inline: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          enable_input_rules: true
          enable_paste_rules: true
          antlers: false
          remove_empty_nodes: false
          display: Media
          type: bard
          icon: bard
          listable: hidden
          instructions_position: above
          visibility: visible
          buttons:
            - removeformat
            - horizontalrule
  seo:
    display: SEO
    fields:
      -
        handle: seo_title
        field:
          input_type: text
          antlers: false
          display: Title
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: seo_keywords
        field:
          antlers: false
          display: Keywords
          type: textarea
          icon: textarea
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: seo_description
        field:
          antlers: false
          display: Description
          type: textarea
          icon: textarea
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: seo_image
        field:
          mode: list
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Image
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
  settings:
    display: Settings
    fields:
      -
        handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
          instructions_position: above
          visibility: visible
          always_save: false
          mode: default
          create: true
      -
        handle: layout
        field:
          hide_partials: true
          blueprint: false
          display: Layout
          type: template
          icon: template
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
          folder: layout
